print("         _____", end='\n')
print("        / ' { >", end='\n')
print("   _____)   (_____", end='\n')
print(" //'--;        ;--'\\\\", end='\n')
print("/////////\\_/\\\\\\\\\\\\\\\\\\\\", end='\n')
print("        m   m")